### ISSUE TITLE
Is Aqara compatible ?

### ISSUE THREAD

**Issue by jeremy-rafflin** [quibusus/node-xiaomi-smart-home#7]
Hi, I use node-xiaomi-smart-home whith a aqara dor sensor and I have this error : 
`/home/pi/gladys-xiaomi-home/node_modules/node-xiaomi-smart-home/build/Hub.js:70
        sensor.heartBeat();
               ^

TypeError: Cannot read property 'heartBeat' of null
    at Hub.onMessage (/home/pi/gladys-xiaomi-home/node_modules/node-xiaomi-smart-home/build/Hub.js:70:16)
    at Socket.emit (events.js:160:13)
    at UDP.onMessage [as onmessage] (dgram.js:658:8)
`

Is the module compatible with Aqara sensors ?

**Comment by quibusus** [comment]
Hi @jeremy-rafflin, please make sure you;re using the latest version 1.1.0

If yes, post your code here
