### ISSUE TITLE
Smoke detector

### ISSUE THREAD

**Issue by Retlawdcp** [quibusus/node-xiaomi-smart-home#8]
Hello,

Is the smoke detector will be compatible with node-xiaomi-smart-home in th future ?

Because when I tried to use it with my domotic, I have this error message : 

```
1|gladys-x | TypeError: Cannot read property 'heartBeat' of null
1|gladys-x |     at Hub.onMessage (/home/pi/gladys-xiaomi-home/node_modules/node-xiaomi-smart-home/build/Hub.js:70:15)
1|gladys-x |     at emitTwo (events.js:106:13)
1|gladys-x |     at Socket.emit (events.js:191:7)
1|gladys-x |     at UDP.onMessage (dgram.js:549:8)
```

Best regards

**Comment by quibusus** [comment]
Hi @Retlawdcp 

I don't have smoke detector to test with - feel free to implement it.

Also, make sure you have the latest version of the module, this looks like a bug that was already fixed.

**Comment by Retlawdcp** [comment]
Hi @quibusus !

Since I updated the module, the error message disappeared, thank you for your help !

But now, there is absolutly nothing in my logs when I use the smoke detector :( 
My domotic don't see the smoke detector...

When I use switch or magnet, I see something in my logs (see bellow), but when the smoke detector is enable or when I press the button, nothing happen...

Unfortunatly I have absolutly no idea how to impllement it (I'm a noob :/ )

(exemple of message in my logs with switch and magnet : 

```
1|gladys-x | Received event "Button" with sid = 158d0001bf6e7e and type = click
1|gladys-x | Received event "Button" with sid = 158d0001bf6e7e and type = double_click
1|gladys-x | Received event "Button" with sid = 158d0001a2397e and type = long_click_press
1|gladys-x | Received event "Button" with sid = 158d0001a2397e and type = long_click_release
1|gladys-x | MAGNET 158d0001d62fb9 false
1|gladys-x | MAGNET 158d0001d62fb9 true
```

**Comment by quibusus** [comment]
@Retlawdcp Sure, try it :) It looks hard, but it is not. If you're a total noob it will take you a few hours but it will be worth it !

Every sensor connected to the gateway has a type and every type of sensors sends the data in its own way. Your goal is to reverse engineer it.  Basically put console.log anywhere you think it could be useful :)

You can use this commit as an example: https://github.com/quibusus/node-xiaomi-smart-home/commit/98cc36b572d7af7d22bba58aeb463682d2d9562f

**Comment by Retlawdcp** [comment]
Thanks @quibusus 

For sure I want try it, i'm total noob but I want learn. But unfortunatly, as I said in my last message, since I updated the module, there is nothing in the logs about smoke detector...

My domotic system normaly catch all who's send by the gateway (open/close magnet and Xiaomi button for example, (cf my last message for logs example) but when the smoke detector have an alarm or when I press smoke detector button, there is nothing in my logs... Not even an error message

**Comment by Retlawdcp** [comment]
Hello,

Smoke Sensor add succesfully. 

I tried to do Pull Request for change listeners.js, hub.ts files and for create new files SmokeSensor.ts, but because I'm noob on github, I don't know my PR is OK.

Have you seen my proposed changes?

**Comment by quibusus** [comment]
Nope, I don't see the PR

Please check help page https://help.github.com/articles/creating-a-pull-request/
and then you can see your PR here
https://github.com/quibusus/node-xiaomi-smart-home/pulls

However, I can now see that also @arosenbach worked on a smoke detector, maybe you can check his branch  https://github.com/arosenbach/node-xiaomi-smart-home and let me know which one is better :)

**Comment by arosenbach** [comment]
Hi guys,

Since @Retlawdcp tested my changes, I created the PR .
Thanks
